---
sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
    - python-docutils
    - libapr1-dev

env:
  - VARNISH_VERSION=4.1.5
  - VARNISH_VERSION=5.0.0

before_install:
  - set -e
  - wget https://repo.varnish-cache.org/source/varnish-${VARNISH_VERSION}.tar.gz
  - tar -zxf varnish-*.tar.gz
  - pushd varnish-*/
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - export VARNISHSRC=$PWD
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4 || (cat ./src/test-suite.log; false)

compiler:
  - gcc
